version: "2.2"
services:
    # App backend service

    db:
        image: mysql:5.7
        container_name: facility_management_db
        volumes:
            - facility_management_db:/var/lib/mysql
        restart: always
        ports:
            - "6001:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 4P2bauIt7WIdpXnd
            MYSQL_DATABASE: facility_management
            MYSQL_PASSWORD: 4P2bauIt7WIdpXnd
        networks:
            network:
                ipv4_address: 172.95.0.2

    app-server:
        # Configuration for building the docker image for the backend service
        container_name: facility_management_be
        build:
            context: sourceCode
            dockerfile: Dockerfile
        ports:
            - 6003:8080 # Forward the exposed port 8080 on the container to port 5002 on the host machine
        restart: always
        depends_on:
            - db # This service depends on mysql. Start that first.
        environment: # Pass environment variables to the service
            - spring.profiles.active=prod
            - spring.datasource.url=jdbc:mysql://db:3306/facility_management?useSSL=false&serverTimezone=UTC
            - spring.datasource.username=root
            - spring.datasource.password=4P2bauIt7WIdpXnd
        networks:
            network:
                ipv4_address: 172.95.0.3

    # for php myadmin goto http://localhost:5001
    phpmyadmino:
        container_name: facility_management_db_phpmyadmin
        depends_on:
            - db
        image: phpmyadmin
        restart: always
        ports:
            - "6002:80"
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: 4P2bauIt7WIdpXnd
        networks:
            network:
                ipv4_address: 172.95.0.4

volumes:
    facility_management_db:

networks:
    network:
        driver: bridge
        ipam:
            config:
                -
                    subnet: 172.95.0.0/16
                    gateway: 172.95.0.1